### ISSUE TITLE
ngCordova plugin module not added

### ISSUE THREAD

**Issue by swathip146** [driftyco/ionic-view-issues#166]
ionic.bundle.js:13380 Uncaught Error: [$injector:modulerr] Failed to instantiate module starter due to:
Error: [$injector:modulerr] Failed to instantiate module ngCordova due to:
Error: [$injector:nomod] Module 'ngCordova' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.3/$injector/nomod?p0=ngCordova
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:13380:12
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:15270:17
    at ensure (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15194:38)
    at module (http://localhost:8100/lib/ionic/js/ionic.bundle.js:15268:14)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17674:22
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13648:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17658:5)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17675:40
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13648:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17658:5)
http://errors.angularjs.org/1.4.3/$injector/modulerr?p0=ngCordova&p1=Error%…%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A17658%3A5)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:13380:12
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17697:15
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13648:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17658:5)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17675:40
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13648:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17658:5)
    at createInjector (http://localhost:8100/lib/ionic/js/ionic.bundle.js:17584:11)
    at doBootstrap (http://localhost:8100/lib/ionic/js/ionic.bundle.js:14942:20)
    at bootstrap (http://localhost:8100/lib/ionic/js/ionic.bundle.js:14963:12)
http://errors.angularjs.org/1.4.3/$injector/modulerr?p0=starter&p1=Error%3A…3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A14963%3A12)

This is the error we get in the developer tools. 
Any help will be deeply appreciated.
Thanks in advance.

**Comment by tlancina** [comment]
Hey thanks for the issue. Since it seems this is not a bug, you may want to try asking for help on the Ionic forums: https://forum.ionicframework.com/, thanks!
